CREATE TABLE [dbo].[Logs]
(
    [Id] BIGINT IDENTITY (1, 1) NOT NULL,
    [Created] DATETIMEOFFSET(7) NOT NULL,
    [Message] VARCHAR(100) NOT NULL,
    [Reference] VARCHAR(36) NOT NULL
    CONSTRAINT [PK_Logs] PRIMARY KEY CLUSTERED ([Id] ASC)
);
